### ISSUE TITLE
realm-cli push -y --project=PROJECT_ID does not create new app when realm_config.json exists

### ISSUE THREAD

**Issue by AllanOricil** [10gen/realm-cli#303]
When realm_config.json file exists in the root of a realm project `realm-cli push -y --project=PROJECT_ID ` does not create a new app like stated in this page https://www.mongodb.com/docs/realm/manage-apps/deploy/automated/sdlc/#std-label-sdlc-create-app. Instead of creating an app, the cli updates the one that is configured in realm_config.js.

If I delete these keys from realm_config.json

````json
"app_id": "test-ehitv",
"name": "test",
````

and then run `realm-cli push -y --project=PROJECT_ID ` it asks me to input the app name

![image](https://user-images.githubusercontent.com/55927613/168331219-cd96cd3c-9326-4f5d-9aee-7c4ea989300f.png)

If I type a name and hit enter, I can finally see a new app in mongodb realm.

My suggestion is to add a new flag called --name in this command. If this flag is passed, then the cli will create or update an app. I thought that --remote would do this, but it only updates an existing app when giving the "app's id". This new flag could also set the app's id instead of generating a weird one.

**Comment by makesitgo** [comment]
Hi @AllanOricil ... thanks for the feedback here!

You're observations on the actual behavior are indeed correct for the current version of the CLI.  The link to documentation you provided is calling that step out as part of an initial setup (and not for a repeated call).  You can notice later in the "Update a Realm App" section that the same command is again listed.

You've already noted on it somewhat, but for the `realm-cli push` command to create a new app, you'll need to first remove the `"app_id"` field out of the project's root configuration file (leaving the `"name"` field should be just fine and serve as a default for the CLI prompt that appears when `-y` is not specified).

One of the features we're actively developing on is to create a better user experience for those that wish to use a single file tree to control changes to multiple Realm apps (effectively letting one `--local` path make calls against many `--remote` app ids).  Using `--remote` like you said would help with existing apps, but we aren't yet in a world where the CLI can use the `push` command to update _or_ create new apps at will (without _some_ manual editing of the app's root configuration file).

Have you looked into the `realm-cli app create` command?  At the expense of actually making changes to the `realm_config.json` file you have present (so maybe run it in an empty directory or one that doesn't contain important project data), you can quickly and iteratively use this command to create many apps up front.  From there, you should have the `"app_id"` values you care about to provide to `--remote` so that you can `push` changes to the apps you wish to update (it also has the `--name` flag you mention).

Hope this helps ... your feedback is valuable here!  While we won't be making any large changes to the current `push` command in the short-term, I think your use case slides in nicely with the framework we've been developing on in order to more seamlessly allow a single file tree to manage multiple Realm apps.

**Comment by AllanOricil** [comment]
The `realm-cli app create` does not work well in my deployment workflows because it also creates an empty project.

My suggestion is to rename this command to `realm-cli app scaffold` as `scaffold` is the more common word for clis that generate files/folders. And use `realm-cli app create` to only create an app inside realm. You can also add a flag to automatically push the local project after creating the app, if one exists.

I have a use case for this change. I have an app that has Values being referenced in Rules. These values are also bind to Secrets. If I try to deploy my app as is, it won't work because those Secrets are missing. To solve this problem I have to deploy an empty app, grab its ID, create secrets and finally push my app. And to achieve this in my deployment pipeline I had to use the API.
