### ISSUE TITLE
supported Realm app locations incomplete

### ISSUE THREAD

**Issue by svenXY** [10gen/realm-cli#329]
Hi,
I have an application with
```json
{
    "app_id": "some-app-gkymj",
    "config_version": 20210101,
    "name": "some-app",
    "location": "DE-FF",
    "provider_region": "gcp-europe-west1",
    "deployment_model": "LOCAL",
    "environment": "testing"
}
```

but I'm not able to recreate it via `push`, as e.g. the field provider_region is not queried.

Other locations are not selectable at all. Is this py purpose, or do I miss something here?

Specifically, I'm interested in selecting GCP Belgium (europe-west-1)

*update*
I tested a little further...
* I can create a new app with pushing my files and selecting DE-FF as location
* but I'm not asked what provider_region I want
* The app is created with "Frankfurt (eu-central-1) • AWS"
* I can then pull this new app
* but after adding the provider_region and trying to push, I get `Deployed app is identical to proposed version, nothing to do`

So it seems this field is completely ignored.

Does that mean that only the locations currently available are usable with realm-cli and that provider_region is also ignored?

**Comment by andrewzlchen** [comment]
Hello Sven, thanks for filing this issue! This is a known issue that we're working actively to fix. 

We plan to deprecate locations in the future in favor of `provider_region` because locations do not take into account what cloud provider the app is using

We will have a new CLI coming soon that addresses this and will prompt for provider and region instead of locations when creating a new app.

But for now, if you wanted to create an application in `gcp-europe-west-1`, you can either:

1. Push an app structure with the `gcp-europe-west1` pre-populated in the `realm_config.json`
2. Create an application as you had been doing and then update the provider_region via the UI via the App Settings > Edit Deployment button

(note that as of today, you cannot change provider_region nor location via the CLI as we're still catching up to the UI in terms of support)

<img width="1835" alt="image" src="https://user-images.githubusercontent.com/15252988/221655506-0670cd31-18a8-49e0-bc2a-710ee5a0436c.png">

Hopefully, this is helpful but if you had any more questions, please feel free to ask!

**Comment by svenXY** [comment]
Hi @andrewzlchen, thanks for your answer. The provided workarounds are good enough for me for the moment and I'm looking forward to the changes you outlined.

Thanks again,
Sven

**Comment by svenXY** [comment]
Hi,

it does not seem to work this way.

I changed realm_config.json to include provider_region (with keeping location at DE-FF), but still end up in AWS. Then I tried without setting location, but then end up with location AWS US-VA and without provider_region.

**Comment by andrewzlchen** [comment]
Hi Sven, 

My apologies - you're right that it actually doesn't behave like that in the `realm-cli`. I didn't realize that change didn't make it into the latest release

Before I file a separate `realm-cli` ticket which will take some time to address, I wanted to ask if the following are acceptable alternatives:

1. Using the UI to change the provider_region after creating the app as shown above
2. Using the [Atlas App Services Admin API](https://www.mongodb.com/docs/atlas/app-services/admin/api/v3/#tag/apps/operation/adminCreateApplication) to create the app first before using the CLI to push changes as you've done before

If neither of the above works, I can file a ticket

**Comment by svenXY** [comment]
One more question: Since I'm using the Api anyway, I could just as well use it to push the application. I have found the API calls to export to a zip file, but how would I use this to push a new app (similar to realm-cli push)?

**Comment by svenXY** [comment]
Alas, I had to make a very kludgy combination of cli and api usage glued with python to get this to work somehow...
